"""create vault_item_audits table

Revision ID: 71e7d978e434
Revises: 
Create Date: 2026-08-02 14:49:01.816473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71e7d978e434'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_item_audits',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_weak', sa.Boolean(), nullable=False),
    sa.Column('warning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crack_time_display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_item_audits_audited_at'), 'vault_item_audits', ['audited_at'], unique=False)
    op.create_index(op.f('ix_vault_item_audits_item_id'), 'vault_item_audits', ['item_id'], unique=False)
    op.create_index(op.f('ix_vault_item_audits_user_id'), 'vault_item_audits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_item_audits_user_id'), table_name='vault_item_audits')
    op.drop_index(op.f('ix_vault_item_audits_item_id'), table_name='vault_item_audits')
    op.drop_index(op.f('ix_vault_item_audits_audited_at'), table_name='vault_item_audits')
    op.drop_table('vault_item_audits')
    # ### end Alembic commands ###
